### ISSUE TITLE
invalid_request

### ISSUE THREAD

**Issue by seppi91** [oderwat/hubic2swiftgate#17]
Since revision 24781fe59537ffff78fe185c59582409474b3e49 something has been changed and it's not possible anymore to register api_access. The redirect_uri always points to https://yourserver.com(:port)/simple.php/callback/ instead of https://yourserver.com(:port)/callback/

A fix for this would be really great. Thx

**Comment by oderwat** [comment]
I just updated how the prefix is calculated. I guess @Christian-Krupa did not test that change or his apache setup is different. Could you test if that works for you again?

**Comment by seppi91** [comment]
Yep, works. Thank you!
