### ISSUE TITLE
SCRIPT_URL does not not exists in nginx / fpm config

### ISSUE THREAD

**Issue by Christian-Krupa** [oderwat/hubic2swiftgate#18]
after updating to commit 215efc99a06fb61e4210ed95ede03d0ef6680b82 i receive this error:
```
Notice: Undefined index: SCRIPT_URL in /hubic2swiftgate/www/simple.php on line 26
```
apache seems to be the only webserver wich supports SCRIPT_URL. php frameworks like symfony2 do use other parameters  (https://github.com/symfony/HttpFoundation/blob/master/Tests/RequestTest.php#L453) to detect the correct "prefix". 

here is my nginx config (with rewrites):
```
server {
    listen 192.168.0.60:443 ssl;
    listen 192.168.0.60:80;
    location / {
        index simple.php;
        rewrite ^/(.*)$ /simple.php?/$1 last;
    }
    location ~ /simple.php($|/) {
        include /opt/local/etc/nginx/fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
    }
}
```

an call to the host https://hub_ic.local with active nginx rewrites return the following `var_dump($_SERVER)` 
```
array(35) {
  ["HOME"]=>
  string(21) "/Users/christiankrupa"
  ["QUERY_STRING"]=>
  string(1) "/"
  ["SCRIPT_NAME"]=>
  string(11) "/simple.php"
  ["REQUEST_URI"]=>
  string(1) "/"
  ["DOCUMENT_URI"]=>
  string(11) "/simple.php"
  ["DOCUMENT_ROOT"]=>
  string(47) "/Users/christiankrupa/Sites/hubic2swiftgate/www"
  ["SERVER_SOFTWARE"]=>
  string(11) "nginx/1.7.7"
  ["SERVER_NAME"]=>
  string(12) "hub_ic.local"
  ["SCRIPT_FILENAME"]=>
  string(58) "/Users/christiankrupa/Sites/hubic2swiftgate/www/simple.php"
  ["PATH_INFO"]=>
  string(11) "/simple.php"
}
```
the same call without rewrites (http://localhost/hubic2swiftgate/www/simple.php)
```
array(33) {
  ["HOME"]=>
  string(21) "/Users/christiankrupa"
  ["QUERY_STRING"]=>
  string(0) ""
  ["SCRIPT_NAME"]=>
  string(31) "/hubic2swiftgate/www/simple.php"
  ["REQUEST_URI"]=>
  string(31) "/hubic2swiftgate/www/simple.php"
  ["DOCUMENT_URI"]=>
  string(31) "/hubic2swiftgate/www/simple.php"
  ["DOCUMENT_ROOT"]=>
  string(27) "/Users/christiankrupa/Sites"
  ["SERVER_SOFTWARE"]=>
  string(11) "nginx/1.7.7"
  ["SCRIPT_FILENAME"]=>
  string(58) "/Users/christiankrupa/Sites/hubic2swiftgate/www/simple.php"
  ["PATH_INFO"]=>
  string(31) "/hubic2swiftgate/www/simple.php"
}
```

what is the apache response? after comparing the params i think we are able to find a valid solution which does work on different webservers.

**Comment by oderwat** [comment]
Well originally I had the prefix hard-coded as empty. Which was changed by your PR. But that did not work with Apache this way.

From comparing the outputs I think that REQUEST_URI is the way to go. As this will follow rewrites and is available everywhere.

**Comment by oderwat** [comment]
I just adjusted it. Can you please try if that works for you?

**Comment by Christian-Krupa** [comment]
nope, does not work. i am going to install an apache beside my nginx, fix it and do a merge request.

**Comment by oderwat** [comment]
What is the problem with the current version on nginx?

**Comment by Christian-Krupa** [comment]
the nginx now detect `/` as `$_prefix` when i call an url with active rewrite (eg. https://hub_ic.local/success/). which results in a invalid `$request` variable like "success/". 
further more each request with parameters like the register site. is detected as a `$request` to `/` which is also not valid and i can not register.

so i do setup a default apache 2.4.7 on ubuntu 14.04.2 lts system and configured the vhost as you describe https://github.com/oderwat/hubic2swiftgate#setting-up-apache2-for-hubic2swiftgate. 

with the current sourcecode i am able to call pages without get parameter eg. `http://192.168.0.10/success/` but i am unable to register `http://192.168.0.10/register/?client=hubic&password=mypasswors`. the `$_prefix` is detected as `/register` and the `$request` is `/`. so i am unable to register again even with an apache and a default php config.


a review of other systems like wordpress (wp-includes/load.php - function wp_fix_server_vars) or symfony2 (symfony/src/Symfony/Component/HttpFoundation/Request.php function prepareBaseUrl) show that the fix is not done in 3-5 lines of code. 

so as a conclusion i think the swift gate should return to a fixed/hardcoded `$_prefix`. this is not the best solution but a pragmatic one.

**Comment by oderwat** [comment]
Yes. I changed it back to the old fixed version but let the order changes such that you can do it in the config file instead of needing to change the main.
