### ISSUE TITLE
Using a recent version of Python-SwiftClient

### ISSUE THREAD

**Issue by pchev** [oderwat/hubic2swiftgate#23]
README.md suggest to use Python-SwiftClient version 1.9 because of a problem with 2.0.
But it look like the problem is solved in recent version, I just do a "pip install python-swiftclient" that install me the version 2.6 and it work fine with Hubic.

The only change I need when moving from 1.9 is to use "export SWIFTCLIENT_INSECURE=true" because my gateway use a self-signed certificate.

Maybe README.md can be updated to avoid people to use an old version when this is not required.
Or is the problem with a specific function I am not using?

**Comment by oderwat** [comment]
I guess that this is fixed indeed. PR for the readme is welcome :)

**Comment by pchev** [comment]
Done.

**Comment by oderwat** [comment]
Sweet! TY!
