### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by jkaberg** [oderwat/hubic2swiftgate#25]
Hi!

Just letting you know this exist, https://github.com/jkaberg/docker-hubic2swiftgate

Should ease the setup part :-)

**Comment by oderwat** [comment]
Cool!

Do you have some time to add it to the docs at "How to get it work?" and make a PR?

It would probably good to have a link to the project here in your readme too.

**Comment by oderwat** [comment]
Added it myself.
