### ISSUE TITLE
ERROR : Access Denied! Wrong Client or Password

### ISSUE THREAD

**Issue by Nico83500** [oderwat/hubic2swiftgate#27]
Hi,
I have this problem with hubic2swiftgate. How can I do to determine the problem ?
Thank you.

**Comment by oderwat** [comment]
You need to use the client and password you stored into the config.php file you created from the example file config.php.sample. This would be "hubic" an "mypassword" for the values in the sample: https://github.com/oderwat/hubic2swiftgate/blob/master/config.php.sample

**Comment by Nico83500** [comment]
Thank you.
I must replace 'hubic' value in config.php ? Or only mypassword ?
And what is the redirection url I should use in hubiC app ? Is http://localhost/ a right value ?

**Comment by oderwat** [comment]
You do not need to replace `hubic` and the password is NOT your hubic password. Chose something else!

The redirection URL for localhost would be: `http://localhost/callback/` if I read my own docs correctly :)

**Comment by Nico83500** [comment]
Ok thanks :)
Now my error is "Illegal! | error: invalid_request | error_description: please verify redirect uri"
Perhaps it's an error with the redirect url from hubiC app. I have put hubic2swiftgate to my VPS, I use http://hsgate.domain.ovh/register....... but I use http://localhost/callback/ because I can't use https://hsgate.domain.ovh/callback/ (hubiC doesn't accept "ovh" in URL...). Right ?

**Comment by oderwat** [comment]
Redirect URI will be: https://github.com/oderwat/hubic2swiftgate/blob/master/www/simple.php#L107

So you could add a `die($redirect_uri.PHP_EOL);` in **line 108** and just call any url on the server to figure our what the gateway sends to HubiC on OAuth2 Register. What is sent there needs to resolve in your Browser. There is no other way! You may need to change your setup.

**Comment by Nico83500** [comment]
Ok thank you for informations.
A last question before changing my setup : if I use a VPS with a 100Mbits network bandwith and a private network with 1Gbit bandwith, does the VPS limit my bandwith ? Or VPS is only use to authenticate and all traffic is made between my home and hubiC server ? If VPS is the bottleneck, it's better to use a local server...

**Comment by oderwat** [comment]
The gateway is only used for the authentication! The data-transfer afterwards is between the client and HubiC server directly.

**Comment by Nico83500** [comment]
Good news, so perhaps the best solution is to buy a new domain name (without .ovh extension) and generate a new hubiC app with the new domain name...

**Comment by oderwat** [comment]
You could just use any DynamicDNS service or just "invent" a domain and add it to the `hosts` file for the systems you want to use it. It is **not** needed that the OVH systems can resolve it.

**Comment by oderwat** [comment]
I close this issue. If you run into more problems reply here please.

**Comment by dezfutak** [comment]
Hi Hans, many thanks for publishing the hubic2swiftgate code on github; I have successfully authenticated a new app with my hubic account using your code, *but* I've so far been completely unsuccessful in using ftp-cloudfs to work with hubic2swiftgate, despite trying many variations :(

Do you have any experience with ftp-cloudfs & hubic2swiftgate (& if so, any help would be welcome!).

Dez.

**Comment by oderwat** [comment]
Hi @dezfutak I would prefer if you open a new issue with your question. I did never use ftp-cloudfs myself so it would be probably better to ask in a fresh issue if anybody else did :)

**Comment by dezfutak** [comment]
@oderwat - yes, that's probably the best solution; as it happens, I've made some progress in that I now understand why things haven't been working (I need to re-authenticate mu app with a subdomain so that ftp-cloudfs  will uniquely resolve on the server in a vhost setup, whereas on the root of a domain, it won't).
