### ISSUE TITLE
Problem registering

### ISSUE THREAD

**Issue by dasmaeh** [oderwat/hubic2swiftgate#35]
I've setup hubic2swiftgate on a devuan virtual server as described in the readme. 
When I try to register the app with hubiC, I get redirected to the hubic2swiftgate homepage not to the success page. The usage page is giving Error 178 without any further details, the apache2 error log is not showing anything.
What can I do to find the error?

**Comment by oderwat** [comment]
Sounds like the callback url you registered at hubic is not correct.

**Comment by dasmaeh** [comment]
Well that's waht I also thought so I double checked.
I'm using https://backups.myserver.de/callback/ as callback url. If I visit this url manually I get an error 'Illegal' and in the logs I find something like this:
```
[Sun Jan 17 09:06:36.203540 2016] [:error] [pid 29890] [client 192.168.3.1:38880] PHP Notice:  Undefined index: error in /var/www/hsgate/www/simple.php on line 382, referer: https://hubic.com/home/browser/developers/
[Sun Jan 17 09:06:36.203688 2016] [:error] [pid 29890] [client 192.168.3.1:38880] PHP Notice:  Undefined index: error_description in /var/www/hsgate/www/simple.php on line 383, referer: https://hubic.com/home/browser/developers/
```

However when I try to register via https://backups.myserver.de/register/?client=hubic&.... I don't get redirected to a hubic login page but directly to https://backups.myserver.de/

To me this looks like something in the redirection doesn' really work.

**Comment by dasmaeh** [comment]
Problem solved.
I am running my hubic2swift gateway behind a SSL proxy (my router using pound), so the function getScheme was returning a wrong scheme for the callback url. My server is accessible over https but in the internal network between router and server communication is not encrypted and using port 80.
So the script was using a different redirect url than hubic, hence the problem.

Maybe you could add an option to allow manually setting the scheme. 

Anyways thanks a lot for this project!

**Comment by oderwat** [comment]
I think we can extend the new configurable callback URL for the autoregister functionality to the normal register function.

**Comment by oderwat** [comment]
I made some changes to the code so that you should be able to add your url into the config.php. Would you please so kind and test if you can get it to work without modifying the main sources now?

**Comment by dasmaeh** [comment]
Works perfectly well. Thank's a lot.
